@startuml
'https://plantuml.com/sequence-diagram

class solution46{
call finder function
display strings and occurence amounts
}
class frequency{
read file
find string and match
next string and repeat
}
@enduml